"""Closure prose → code, and the fail-safe when it cannot be classified."""

from __future__ import annotations

from swimzh.domain.closure import ClosureCode, classify_closure, is_unmapped


def test_every_curated_phrase_in_the_repo_is_classified() -> None:
    """The phrases actually authored in `data/pools/*.yaml` today.

    Pinned so that adding a pool with a NEW phrase is a visible decision (extend the code
    set) rather than a silent drop to `UNMAPPED`. This is the mirror of the
    `REPRESENTATIVE_ACCESS` completeness idiom, applied to curated data.
    """
    curated = {
        "Sommerpause": ClosureCode.SEASONAL_BREAK,
        "Sommerpause / Revision": ClosureCode.SEASONAL_BREAK_MAINTENANCE,
        "Betriebsferien": ClosureCode.OPERATIONAL_BREAK,
        "Heiligabend": ClosureCode.CHRISTMAS_EVE,
    }
    for phrase, expected in curated.items():
        code, params = classify_closure(phrase)
        assert code is expected, phrase
        assert params == {}, "a recognised phrase needs no passthrough text"
        assert not is_unmapped(code)


def test_matching_ignores_surrounding_space_and_case() -> None:
    """These are hand-authored YAML strings; a stray space must not cost a code."""
    assert classify_closure("  Sommerpause  ")[0] is ClosureCode.SEASONAL_BREAK
    assert classify_closure("SOMMERPAUSE")[0] is ClosureCode.SEASONAL_BREAK


def test_an_unknown_phrase_fails_SAFE_carrying_the_original_through() -> None:
    """The honesty invariant: we never blank a reason we failed to understand.

    An unrecognised phrase becomes UNMAPPED with the German verbatim in `params.text`, so
    the UI can still say something TRUE ("Closed · <phrase>") — the same idiom as
    `LanePlanUnavailable`, which persists the failure instead of dropping the row.
    """
    code, params = classify_closure("Wasserschaden")
    assert code is ClosureCode.UNMAPPED
    assert is_unmapped(code)
    assert params == {"text": "Wasserschaden"}


def test_a_closure_with_no_stated_reason_is_SPECIAL_not_unmapped() -> None:
    """Empty is a real, nameable state — not a classification failure. Conflating the two
    would make the build audit cry wolf on every reasonless closure."""
    for empty in ("", "   ", None):
        code, params = classify_closure(empty)
        assert code is ClosureCode.SPECIAL
        assert not is_unmapped(code)
        assert params == {}


def test_resolver_only_codes_are_never_produced_from_prose() -> None:
    """PUBLIC_HOLIDAY / NO_SESSIONS are generated by the resolver, never parsed out of
    curated text — otherwise a pool could author its way into a state the domain owns."""
    resolver_only = {ClosureCode.PUBLIC_HOLIDAY, ClosureCode.NO_SESSIONS}
    for phrase in ("public holiday", "Feiertag", "no sessions scheduled", "Neujahr"):
        code, _ = classify_closure(phrase)
        assert code not in resolver_only, phrase
