// Catalog.generated.swift — GENERATED by scripts/locales_to_xcstrings.mjs. Do not edit.
//
// The argument shape of every message in `Resources/Localizable.xcstrings`.
//
// Foundation's compiled catalog is positional: `%1$@`, `%2$@`. The placeholder NAMES
// (`{hhmm}`, `{total}`) exist only in the web catalogs this file is generated from, so a
// Swift call site that passes a dictionary needs the ordering from somewhere. This is that
// somewhere, written by the same pass that numbered the specifiers.
//
// `isPlural` decides which lookup Foundation needs: a plural entry compiles to a
// `.stringsdict` whose format must be expanded by `String(format:locale:)` with the
// READER'S locale — the bundle picks the language, the locale picks the plural rule, and
// getting only one of them right renders Polish with English grammar (see Localized.swift).

extension Catalog {
  /// One positional argument: the name the catalogs use for it, and how it is rendered.
  public struct Parameter: Sendable, Equatable {
    public enum Kind: Sendable, Equatable {
      /// Rendered with `%lld` — the plural-selecting count.
      case integer
      /// Rendered with `%@` — an already-formatted value (a time, a place, a price).
      case text
    }
    public let name: String
    public let kind: Kind
    public init(name: String, kind: Kind) {
      self.name = name
      self.kind = kind
    }
  }

  /// What one message expects: its arguments, in the order the format string numbers them.
  public struct Entry: Sendable, Equatable {
    public let parameters: [Parameter]
    public let isPlural: Bool
    public init(parameters: [Parameter], isPlural: Bool) {
      self.parameters = parameters
      self.isPlural = isPlural
    }
  }

  /// Every key in the catalog, with its argument shape.
  public static let entries: [String: Entry] = [
    "a11y.blockLabel": Entry(
      parameters: [
        Parameter(name: "start", kind: .text),
        Parameter(name: "end", kind: .text),
        Parameter(name: "access", kind: .text),
      ], isPlural: false),
    "a11y.fact.laneData": Entry(parameters: [], isPlural: false),
    "a11y.fact.laneSplit": Entry(parameters: [], isPlural: false),
    "a11y.fact.lanes": Entry(parameters: [], isPlural: false),
    "a11y.fact.publicLanes": Entry(parameters: [], isPlural: false),
    "a11y.fact.reservedBy": Entry(parameters: [], isPlural: false),
    "a11y.selected": Entry(parameters: [], isPlural: false),
    "a11y.value.laneDataIncomplete": Entry(parameters: [], isPlural: false),
    "a11y.value.laneSplitUnpublished": Entry(parameters: [], isPlural: false),
    "a11y.value.ofTotal": Entry(
      parameters: [
        Parameter(name: "public", kind: .text),
        Parameter(name: "total", kind: .text),
      ], isPlural: false),
    "a11y.value.ownerAndOthers": Entry(
      parameters: [
        Parameter(name: "owner", kind: .text)
      ], isPlural: false),
    "access.accompanied": Entry(parameters: [], isPlural: false),
    "access.accompanied.desc": Entry(parameters: [], isPlural: false),
    "access.adults": Entry(parameters: [], isPlural: false),
    "access.adults.desc": Entry(parameters: [], isPlural: false),
    "access.club": Entry(parameters: [], isPlural: false),
    "access.club.desc": Entry(parameters: [], isPlural: false),
    "access.family": Entry(parameters: [], isPlural: false),
    "access.family.desc": Entry(parameters: [], isPlural: false),
    "access.genderDiverse": Entry(parameters: [], isPlural: false),
    "access.genderDiverse.desc": Entry(parameters: [], isPlural: false),
    "access.girls": Entry(parameters: [], isPlural: false),
    "access.girls.desc": Entry(parameters: [], isPlural: false),
    "access.lane": Entry(parameters: [], isPlural: false),
    "access.lane.desc": Entry(parameters: [], isPlural: false),
    "access.public": Entry(parameters: [], isPlural: false),
    "access.public.desc": Entry(parameters: [], isPlural: false),
    "access.school": Entry(parameters: [], isPlural: false),
    "access.school.desc": Entry(parameters: [], isPlural: false),
    "access.seniors": Entry(parameters: [], isPlural: false),
    "access.seniors.desc": Entry(parameters: [], isPlural: false),
    "access.unknown": Entry(parameters: [], isPlural: false),
    "access.women": Entry(parameters: [], isPlural: false),
    "access.women.desc": Entry(parameters: [], isPlural: false),
    "accessTypes.footer": Entry(parameters: [], isPlural: false),
    "accessTypes.title": Entry(parameters: [], isPlural: false),
    "action.done": Entry(parameters: [], isPlural: false),
    "action.favourite": Entry(parameters: [], isPlural: false),
    "action.hideLanePlan": Entry(parameters: [], isPlural: false),
    "action.showLanePlan": Entry(parameters: [], isPlural: false),
    "action.unfavourite": Entry(parameters: [], isPlural: false),
    "admission.free": Entry(parameters: [], isPlural: false),
    "admission.tariff": Entry(parameters: [], isPlural: false),
    "admission.unknown": Entry(parameters: [], isPlural: false),
    "age.days": Entry(
      parameters: [
        Parameter(name: "count", kind: .integer)
      ], isPlural: true),
    "age.hours": Entry(
      parameters: [
        Parameter(name: "count", kind: .text)
      ], isPlural: false),
    "age.minutes": Entry(
      parameters: [
        Parameter(name: "count", kind: .text)
      ], isPlural: false),
    "app.title": Entry(parameters: [], isPlural: false),
    "badge.metres": Entry(
      parameters: [
        Parameter(name: "length", kind: .text)
      ], isPlural: false),
    "badge.poolAria": Entry(
      parameters: [
        Parameter(name: "length", kind: .text),
        Parameter(name: "lanes", kind: .text),
      ], isPlural: false),
    "badge.teachingPool": Entry(parameters: [], isPlural: false),
    "banner.calendarCoverage.title": Entry(parameters: [], isPlural: false),
    "banner.generic.title": Entry(parameters: [], isPlural: false),
    "banner.holidayHoursUnverified.title": Entry(parameters: [], isPlural: false),
    "basin.fact.diving": Entry(parameters: [], isPlural: false),
    "basin.fact.lanePlan": Entry(parameters: [], isPlural: false),
    "basin.fact.lanes": Entry(parameters: [], isPlural: false),
    "basin.fact.size": Entry(parameters: [], isPlural: false),
    "basin.fact.water": Entry(parameters: [], isPlural: false),
    "basin.laneCount": Entry(
      parameters: [
        Parameter(name: "count", kind: .integer)
      ], isPlural: true),
    "basin.parsedProseCaveat": Entry(parameters: [], isPlural: false),
    "basin.size.length": Entry(
      parameters: [
        Parameter(name: "length", kind: .text)
      ], isPlural: false),
    "basin.size.lengthByWidth": Entry(
      parameters: [
        Parameter(name: "length", kind: .text),
        Parameter(name: "width", kind: .text),
      ], isPlural: false),
    "basin.size.width": Entry(
      parameters: [
        Parameter(name: "width", kind: .text)
      ], isPlural: false),
    "basin.tempNominalCaveat": Entry(parameters: [], isPlural: false),
    "basinKind.diving": Entry(parameters: [], isPlural: false),
    "basinKind.learner": Entry(parameters: [], isPlural: false),
    "basinKind.multi_purpose": Entry(parameters: [], isPlural: false),
    "basinKind.non_swimmer": Entry(parameters: [], isPlural: false),
    "basinKind.outdoor": Entry(parameters: [], isPlural: false),
    "basinKind.paddling": Entry(parameters: [], isPlural: false),
    "basinKind.swimmer": Entry(parameters: [], isPlural: false),
    "basinKind.thermal": Entry(parameters: [], isPlural: false),
    "basinKind.unknown": Entry(
      parameters: [
        Parameter(name: "kind", kind: .text)
      ], isPlural: false),
    "board.hoursNotListed": Entry(parameters: [], isPlural: false),
    "board.nearestFirst": Entry(parameters: [], isPlural: false),
    "board.noSessionsGroup": Entry(parameters: [], isPlural: false),
    "board.poolCount": Entry(
      parameters: [
        Parameter(name: "count", kind: .integer)
      ], isPlural: true),
    "browser.allKinds": Entry(parameters: [], isPlural: false),
    "browser.filterByKind": Entry(parameters: [], isPlural: false),
    "browser.kind": Entry(parameters: [], isPlural: false),
    "browser.noMatch.body": Entry(parameters: [], isPlural: false),
    "closure.christmas_eve": Entry(parameters: [], isPlural: false),
    "closure.maintenance": Entry(parameters: [], isPlural: false),
    "closure.no_sessions": Entry(parameters: [], isPlural: false),
    "closure.operational_break": Entry(parameters: [], isPlural: false),
    "closure.out_of_season": Entry(parameters: [], isPlural: false),
    "closure.public_holiday": Entry(parameters: [], isPlural: false),
    "closure.public_holiday_named": Entry(
      parameters: [
        Parameter(name: "holiday", kind: .text)
      ], isPlural: false),
    "closure.seasonal_break": Entry(parameters: [], isPlural: false),
    "closure.seasonal_break_maintenance": Entry(parameters: [], isPlural: false),
    "closure.special": Entry(parameters: [], isPlural: false),
    "closure.unmapped": Entry(
      parameters: [
        Parameter(name: "text", kind: .text)
      ], isPlural: false),
    "closureClause.closure": Entry(parameters: [], isPlural: false),
    "closureClause.no_sessions": Entry(parameters: [], isPlural: false),
    "closureClause.out_of_season": Entry(parameters: [], isPlural: false),
    "closureClause.unknown": Entry(
      parameters: [
        Parameter(name: "reason", kind: .text)
      ], isPlural: false),
    "combo.noMatches": Entry(parameters: [], isPlural: false),
    "combo.noPoolsMatch": Entry(parameters: [], isPlural: false),
    "common.today": Entry(parameters: [], isPlural: false),
    "date.nextDay": Entry(parameters: [], isPlural: false),
    "date.nextWeek": Entry(parameters: [], isPlural: false),
    "date.previousDay": Entry(parameters: [], isPlural: false),
    "date.previousWeek": Entry(parameters: [], isPlural: false),
    "date.selectedDay": Entry(parameters: [], isPlural: false),
    "date.selectedWeek": Entry(parameters: [], isPlural: false),
    "date.weekOf": Entry(
      parameters: [
        Parameter(name: "date", kind: .text)
      ], isPlural: false),
    "detail.checked": Entry(
      parameters: [
        Parameter(name: "date", kind: .text)
      ], isPlural: false),
    "detail.closedNote": Entry(
      parameters: [
        Parameter(name: "reason", kind: .text),
        Parameter(name: "note", kind: .text),
      ], isPlural: false),
    "detail.closedReason": Entry(
      parameters: [
        Parameter(name: "reason", kind: .text)
      ], isPlural: false),
    "detail.emptyPanel": Entry(parameters: [], isPlural: false),
    "detail.fact.about": Entry(parameters: [], isPlural: false),
    "detail.fact.address": Entry(parameters: [], isPlural: false),
    "detail.fact.basin": Entry(parameters: [], isPlural: false),
    "detail.fact.busyness": Entry(parameters: [], isPlural: false),
    "detail.fact.distance": Entry(parameters: [], isPlural: false),
    "detail.fact.eligibility": Entry(parameters: [], isPlural: false),
    "detail.fact.entry": Entry(parameters: [], isPlural: false),
    "detail.fact.freshness": Entry(parameters: [], isPlural: false),
    "detail.fact.lastAdmission": Entry(parameters: [], isPlural: false),
    "detail.fact.liveWater": Entry(parameters: [], isPlural: false),
    "detail.fact.phone": Entry(parameters: [], isPlural: false),
    "detail.fact.price": Entry(parameters: [], isPlural: false),
    "detail.fact.pricesRead": Entry(parameters: [], isPlural: false),
    "detail.fact.schedule": Entry(parameters: [], isPlural: false),
    "detail.fact.season": Entry(parameters: [], isPlural: false),
    "detail.fact.tariffPage": Entry(parameters: [], isPlural: false),
    "detail.fact.today": Entry(parameters: [], isPlural: false),
    "detail.fact.water": Entry(parameters: [], isPlural: false),
    "detail.fact.website": Entry(parameters: [], isPlural: false),
    "detail.fact.yourRate": Entry(parameters: [], isPlural: false),
    "detail.headline": Entry(
      parameters: [
        Parameter(name: "total", kind: .text),
        Parameter(name: "hhmm", kind: .text),
      ], isPlural: false),
    "detail.headlineAria": Entry(
      parameters: [
        Parameter(name: "public", kind: .text),
        Parameter(name: "total", kind: .text),
        Parameter(name: "hhmm", kind: .text),
        Parameter(name: "peak", kind: .text),
      ], isPlural: false),
    "detail.hoursUnknown": Entry(parameters: [], isPlural: false),
    "detail.lastAdmission.value": Entry(
      parameters: [
        Parameter(name: "duration", kind: .text)
      ], isPlural: false),
    "detail.liveClosed": Entry(parameters: [], isPlural: false),
    "detail.liveMeasuredAgo": Entry(
      parameters: [
        Parameter(name: "age", kind: .text)
      ], isPlural: false),
    "detail.liveOpen": Entry(parameters: [], isPlural: false),
    "detail.noPublicLanes": Entry(parameters: [], isPlural: false),
    "detail.notAvailable": Entry(parameters: [], isPlural: false),
    "detail.notAvailableYet": Entry(parameters: [], isPlural: false),
    "detail.notDated": Entry(parameters: [], isPlural: false),
    "detail.notListed": Entry(parameters: [], isPlural: false),
    "detail.notShown": Entry(parameters: [], isPlural: false),
    "detail.notYetMeasured": Entry(parameters: [], isPlural: false),
    "detail.note.closed": Entry(parameters: [], isPlural: false),
    "detail.note.lanesUnknown": Entry(parameters: [], isPlural: false),
    "detail.note.uncurated": Entry(parameters: [], isPlural: false),
    "detail.openLaneSplit": Entry(parameters: [], isPlural: false),
    "detail.openRange": Entry(
      parameters: [
        Parameter(name: "from", kind: .text),
        Parameter(name: "to", kind: .text),
      ], isPlural: false),
    "detail.peakNote": Entry(
      parameters: [
        Parameter(name: "peak", kind: .text),
        Parameter(name: "total", kind: .text),
      ], isPlural: false),
    "detail.pool": Entry(parameters: [], isPlural: false),
    "detail.section.admission": Entry(parameters: [], isPlural: false),
    "detail.section.basins": Entry(parameters: [], isPlural: false),
    "detail.section.features": Entry(parameters: [], isPlural: false),
    "detail.section.lanes": Entry(parameters: [], isPlural: false),
    "detail.section.lockers": Entry(parameters: [], isPlural: false),
    "detail.section.provenance": Entry(parameters: [], isPlural: false),
    "detail.section.rentals": Entry(parameters: [], isPlural: false),
    "detail.section.season": Entry(parameters: [], isPlural: false),
    "detail.section.where": Entry(parameters: [], isPlural: false),
    "detail.tempMeasured": Entry(parameters: [], isPlural: false),
    "detail.tempNominal": Entry(parameters: [], isPlural: false),
    "detail.waterNotPublished": Entry(parameters: [], isPlural: false),
    "detail.weekButton": Entry(parameters: [], isPlural: false),
    "elig.chk": Entry(parameters: [], isPlural: false),
    "elig.chk.short": Entry(parameters: [], isPlural: false),
    "elig.in": Entry(parameters: [], isPlural: false),
    "elig.no": Entry(parameters: [], isPlural: false),
    "error.store.body": Entry(parameters: [], isPlural: false),
    "error.store.title": Entry(parameters: [], isPlural: false),
    "feature.closed": Entry(
      parameters: [
        Parameter(name: "reason", kind: .text)
      ], isPlural: false),
    "feature.fact.hours": Entry(parameters: [], isPlural: false),
    "feature.fact.surcharge": Entry(parameters: [], isPlural: false),
    "feature.fact.temperature": Entry(parameters: [], isPlural: false),
    "feature.hoursNotListed": Entry(parameters: [], isPlural: false),
    "featureKind.gastronomy": Entry(parameters: [], isPlural: false),
    "featureKind.playground": Entry(parameters: [], isPlural: false),
    "featureKind.sauna": Entry(parameters: [], isPlural: false),
    "featureKind.slide": Entry(parameters: [], isPlural: false),
    "featureKind.sport": Entry(parameters: [], isPlural: false),
    "featureKind.sunbathing": Entry(parameters: [], isPlural: false),
    "featureKind.unknown": Entry(
      parameters: [
        Parameter(name: "kind", kind: .text)
      ], isPlural: false),
    "featureKind.wellness": Entry(parameters: [], isPlural: false),
    "fee.amount": Entry(
      parameters: [
        Parameter(name: "amount", kind: .text)
      ], isPlural: false),
    "fee.deposit": Entry(
      parameters: [
        Parameter(name: "amount", kind: .text)
      ], isPlural: false),
    "fee.free": Entry(parameters: [], isPlural: false),
    "fee.perPeriod": Entry(
      parameters: [
        Parameter(name: "period", kind: .text)
      ], isPlural: false),
    "fee.unstated": Entry(parameters: [], isPlural: false),
    "filter.allKinds": Entry(parameters: [], isPlural: false),
    "filter.anyDistance": Entry(parameters: [], isPlural: false),
    "filter.eligibleOnly": Entry(parameters: [], isPlural: false),
    "filter.eligibleOnly.toggle": Entry(parameters: [], isPlural: false),
    "filter.favourites": Entry(parameters: [], isPlural: false),
    "filter.favouritesOnly.toggle": Entry(parameters: [], isPlural: false),
    "filter.measureFrom": Entry(parameters: [], isPlural: false),
    "filter.none": Entry(parameters: [], isPlural: false),
    "filter.poolKinds": Entry(parameters: [], isPlural: false),
    "filter.section.what": Entry(parameters: [], isPlural: false),
    "filter.section.where": Entry(parameters: [], isPlural: false),
    "filter.section.who": Entry(parameters: [], isPlural: false),
    "filter.within": Entry(parameters: [], isPlural: false),
    "freshness.awaiting": Entry(parameters: [], isPlural: false),
    "freshness.awaiting.caveat": Entry(parameters: [], isPlural: false),
    "freshness.noSource": Entry(parameters: [], isPlural: false),
    "freshness.noSource.caveat": Entry(parameters: [], isPlural: false),
    "freshness.scraped": Entry(parameters: [], isPlural: false),
    "freshness.unknown": Entry(
      parameters: [
        Parameter(name: "state", kind: .text)
      ], isPlural: false),
    "freshness.unknown.caveat": Entry(parameters: [], isPlural: false),
    "gantt.lane": Entry(
      parameters: [
        Parameter(name: "lane", kind: .text)
      ], isPlural: false),
    "gantt.public": Entry(parameters: [], isPlural: false),
    "gantt.readout": Entry(
      parameters: [
        Parameter(name: "hhmm", kind: .text),
        Parameter(name: "public", kind: .text),
        Parameter(name: "total", kind: .text),
      ], isPlural: false),
    "gantt.reserved": Entry(parameters: [], isPlural: false),
    "gantt.title": Entry(parameters: [], isPlural: false),
    "header.copied": Entry(parameters: [], isPlural: false),
    "header.copyAria": Entry(parameters: [], isPlural: false),
    "header.copyLink": Entry(parameters: [], isPlural: false),
    "header.language": Entry(parameters: [], isPlural: false),
    "header.themeAria": Entry(
      parameters: [
        Parameter(name: "theme", kind: .text)
      ], isPlural: false),
    "headline.poolsWithSessions": Entry(
      parameters: [
        Parameter(name: "count", kind: .integer)
      ], isPlural: true),
    "holiday.ascension": Entry(parameters: [], isPlural: false),
    "holiday.berchtoldstag": Entry(parameters: [], isPlural: false),
    "holiday.christmas": Entry(parameters: [], isPlural: false),
    "holiday.easter_monday": Entry(parameters: [], isPlural: false),
    "holiday.good_friday": Entry(parameters: [], isPlural: false),
    "holiday.labour_day": Entry(parameters: [], isPlural: false),
    "holiday.national_day": Entry(parameters: [], isPlural: false),
    "holiday.new_year": Entry(parameters: [], isPlural: false),
    "holiday.st_stephens": Entry(parameters: [], isPlural: false),
    "holiday.unknown": Entry(
      parameters: [
        Parameter(name: "holiday", kind: .text)
      ], isPlural: false),
    "holiday.whit_monday": Entry(parameters: [], isPlural: false),
    "insight.bestWindow": Entry(
      parameters: [
        Parameter(name: "public", kind: .text),
        Parameter(name: "total", kind: .text),
        Parameter(name: "facility", kind: .text),
        Parameter(name: "start", kind: .text),
        Parameter(name: "end", kind: .text),
      ], isPlural: false),
    "insight.coverage": Entry(
      parameters: [
        Parameter(name: "closed", kind: .text),
        Parameter(name: "unlisted", kind: .text),
      ], isPlural: false),
    "insight.day.none": Entry(parameters: [], isPlural: false),
    "insight.day.pools": Entry(
      parameters: [
        Parameter(name: "count", kind: .integer)
      ], isPlural: true),
    "insight.noSplit": Entry(parameters: [], isPlural: false),
    "insight.noSplit.label": Entry(parameters: [], isPlural: false),
    "insight.pool.none": Entry(
      parameters: [
        Parameter(name: "facility", kind: .text)
      ], isPlural: false),
    "insight.pool.openDays": Entry(
      parameters: [
        Parameter(name: "count", kind: .integer)
      ], isPlural: true),
    "insight.pool.reliable": Entry(
      parameters: [
        Parameter(name: "facility", kind: .text),
        Parameter(name: "public", kind: .text),
        Parameter(name: "total", kind: .text),
        Parameter(name: "start", kind: .text),
      ], isPlural: false),
    "insight.pool.thisPool": Entry(parameters: [], isPlural: false),
    "lane.incompleteCaveat": Entry(parameters: [], isPlural: false),
    "lane.nonePublic": Entry(parameters: [], isPlural: false),
    "lane.nonePublic.partial": Entry(parameters: [], isPlural: false),
    "lane.openToPublic": Entry(parameters: [], isPlural: false),
    "lane.publicOfTotal": Entry(
      parameters: [
        Parameter(name: "public", kind: .text),
        Parameter(name: "count", kind: .integer),
      ], isPlural: true),
    "lane.publicOfTotal.partial": Entry(
      parameters: [
        Parameter(name: "public", kind: .text),
        Parameter(name: "count", kind: .integer),
      ], isPlural: true),
    "lane.spoken": Entry(
      parameters: [
        Parameter(name: "lane", kind: .text),
        Parameter(name: "start", kind: .text),
        Parameter(name: "end", kind: .text),
        Parameter(name: "holder", kind: .text),
      ], isPlural: false),
    "legend.group.availability": Entry(parameters: [], isPlural: false),
    "legend.group.forYou": Entry(parameters: [], isPlural: false),
    "legend.group.laneStack": Entry(parameters: [], isPlural: false),
    "legend.group.sessionType": Entry(parameters: [], isPlural: false),
    "legend.honestyNote": Entry(parameters: [], isPlural: false),
    "legend.label": Entry(parameters: [], isPlural: false),
    "legend.lane.best": Entry(parameters: [], isPlural: false),
    "legend.lane.public": Entry(parameters: [], isPlural: false),
    "legend.lane.reserved": Entry(parameters: [], isPlural: false),
    "legend.lane.unpublished": Entry(parameters: [], isPlural: false),
    "legend.state.closed": Entry(parameters: [], isPlural: false),
    "legend.state.open": Entry(parameters: [], isPlural: false),
    "legend.state.unknown": Entry(parameters: [], isPlural: false),
    "live.no_key": Entry(parameters: [], isPlural: false),
    "live.not_configured": Entry(parameters: [], isPlural: false),
    "live.provider_error": Entry(parameters: [], isPlural: false),
    "lockerKind.cabin": Entry(parameters: [], isPlural: false),
    "lockerKind.unknown": Entry(
      parameters: [
        Parameter(name: "kind", kind: .text)
      ], isPlural: false),
    "lockerKind.valuables": Entry(parameters: [], isPlural: false),
    "lockerKind.wardrobe": Entry(parameters: [], isPlural: false),
    "meta.answersThrough": Entry(parameters: [], isPlural: false),
    "meta.dataFrom": Entry(parameters: [], isPlural: false),
    "meta.offlineNote": Entry(parameters: [], isPlural: false),
    "mobile.filters": Entry(parameters: [], isPlural: false),
    "mobile.lanePlan": Entry(parameters: [], isPlural: false),
    "mobile.lanesUntil": Entry(
      parameters: [
        Parameter(name: "public", kind: .text),
        Parameter(name: "total", kind: .text),
        Parameter(name: "hhmm", kind: .text),
      ], isPlural: false),
    "mobile.openToYou": Entry(
      parameters: [
        Parameter(name: "count", kind: .integer)
      ], isPlural: true),
    "mobile.openToYouOn": Entry(
      parameters: [
        Parameter(name: "count", kind: .integer),
        Parameter(name: "day", kind: .text),
      ], isPlural: true),
    "mobile.tier.closed": Entry(parameters: [], isPlural: false),
    "mobile.tier.now": Entry(parameters: [], isPlural: false),
    "mobile.tier.soon": Entry(parameters: [], isPlural: false),
    "mobile.tier.unknown": Entry(parameters: [], isPlural: false),
    "mobile.today": Entry(parameters: [], isPlural: false),
    "mobile.verdict.closedAllDay": Entry(parameters: [], isPlural: false),
    "mobile.verdict.doneForToday": Entry(parameters: [], isPlural: false),
    "mobile.verdict.hoursUnknown": Entry(parameters: [], isPlural: false),
    "mobile.verdict.notYoursUntil": Entry(
      parameters: [
        Parameter(name: "hhmm", kind: .text)
      ], isPlural: false),
    "mobile.verdict.openNow": Entry(parameters: [], isPlural: false),
    "mobile.verdict.opensAt": Entry(
      parameters: [
        Parameter(name: "hhmm", kind: .text)
      ], isPlural: false),
    "mobile.verdict.partlyReserved": Entry(parameters: [], isPlural: false),
    "mobile.verdict.untilTime": Entry(
      parameters: [
        Parameter(name: "hhmm", kind: .text)
      ], isPlural: false),
    "nav.accessTypes": Entry(parameters: [], isPlural: false),
    "nav.allPools": Entry(parameters: [], isPlural: false),
    "nav.browse": Entry(parameters: [], isPlural: false),
    "nav.findAPool": Entry(parameters: [], isPlural: false),
    "panel.bestWindow": Entry(
      parameters: [
        Parameter(name: "start", kind: .text),
        Parameter(name: "end", kind: .text),
        Parameter(name: "count", kind: .integer),
      ], isPlural: true),
    "panel.clubSlot.manyLanes": Entry(
      parameters: [
        Parameter(name: "start", kind: .text),
        Parameter(name: "end", kind: .text),
        Parameter(name: "lanes", kind: .text),
      ], isPlural: false),
    "panel.clubSlot.oneLane": Entry(
      parameters: [
        Parameter(name: "start", kind: .text),
        Parameter(name: "end", kind: .text),
        Parameter(name: "lanes", kind: .text),
      ], isPlural: false),
    "pill.closed": Entry(parameters: [], isPlural: false),
    "pill.open": Entry(parameters: [], isPlural: false),
    "pill.opensLater": Entry(parameters: [], isPlural: false),
    "pill.unknown": Entry(parameters: [], isPlural: false),
    "place.anywhere": Entry(parameters: [], isPlural: false),
    "place.hb": Entry(parameters: [], isPlural: false),
    "place.myLocation": Entry(parameters: [], isPlural: false),
    "place.searchPrompt": Entry(parameters: [], isPlural: false),
    "place.useMyLocation": Entry(parameters: [], isPlural: false),
    "poolKind.indoor": Entry(parameters: [], isPlural: false),
    "poolKind.lake": Entry(parameters: [], isPlural: false),
    "poolKind.outdoor": Entry(parameters: [], isPlural: false),
    "poolKind.paddling": Entry(parameters: [], isPlural: false),
    "poolKind.river": Entry(parameters: [], isPlural: false),
    "poolKind.school": Entry(parameters: [], isPlural: false),
    "poolKind.thermal": Entry(parameters: [], isPlural: false),
    "poolKind.unknown": Entry(
      parameters: [
        Parameter(name: "kind", kind: .text)
      ], isPlural: false),
    "price.adult": Entry(
      parameters: [
        Parameter(name: "amount", kind: .text)
      ], isPlural: false),
    "price.child": Entry(
      parameters: [
        Parameter(name: "amount", kind: .text)
      ], isPlural: false),
    "price.minAgeCaveat": Entry(
      parameters: [
        Parameter(name: "minAge", kind: .text)
      ], isPlural: false),
    "price.senior": Entry(
      parameters: [
        Parameter(name: "amount", kind: .text)
      ], isPlural: false),
    "price.staleCaveat": Entry(parameters: [], isPlural: false),
    "price.youth": Entry(
      parameters: [
        Parameter(name: "amount", kind: .text)
      ], isPlural: false),
    "priceCategory.adult": Entry(parameters: [], isPlural: false),
    "priceCategory.child": Entry(parameters: [], isPlural: false),
    "priceCategory.senior": Entry(parameters: [], isPlural: false),
    "priceCategory.unknown": Entry(
      parameters: [
        Parameter(name: "category", kind: .text)
      ], isPlural: false),
    "priceCategory.youth": Entry(parameters: [], isPlural: false),
    "prov.awaiting": Entry(parameters: [], isPlural: false),
    "prov.curated.no": Entry(parameters: [], isPlural: false),
    "prov.curated.yes": Entry(parameters: [], isPlural: false),
    "prov.fact.accurateAsOf": Entry(parameters: [], isPlural: false),
    "prov.fact.curation": Entry(parameters: [], isPlural: false),
    "prov.fact.readFrom": Entry(parameters: [], isPlural: false),
    "prov.lastChecked": Entry(
      parameters: [
        Parameter(name: "date", kind: .text)
      ], isPlural: false),
    "prov.noSource": Entry(parameters: [], isPlural: false),
    "prov.scraped": Entry(parameters: [], isPlural: false),
    "rentalKind.deck_chair": Entry(parameters: [], isPlural: false),
    "rentalKind.locker": Entry(parameters: [], isPlural: false),
    "rentalKind.swim_aid": Entry(parameters: [], isPlural: false),
    "rentalKind.towel": Entry(parameters: [], isPlural: false),
    "rentalKind.unknown": Entry(
      parameters: [
        Parameter(name: "kind", kind: .text)
      ], isPlural: false),
    "row.moreThatDay": Entry(
      parameters: [
        Parameter(name: "count", kind: .text)
      ], isPlural: false),
    "row.moreToday": Entry(
      parameters: [
        Parameter(name: "count", kind: .text)
      ], isPlural: false),
    "season.fairWeatherCaveat": Entry(parameters: [], isPlural: false),
    "season.range": Entry(
      parameters: [
        Parameter(name: "from", kind: .text),
        Parameter(name: "to", kind: .text),
      ], isPlural: false),
    "season.rangeWithDays": Entry(
      parameters: [
        Parameter(name: "startDay", kind: .text),
        Parameter(name: "from", kind: .text),
        Parameter(name: "endDay", kind: .text),
        Parameter(name: "to", kind: .text),
      ], isPlural: false),
    "session.fairWeather": Entry(
      parameters: [
        Parameter(name: "spans", kind: .text)
      ], isPlural: false),
    "session.fairWeather.badge": Entry(parameters: [], isPlural: false),
    "sources.chipAria": Entry(
      parameters: [
        Parameter(name: "name", kind: .text),
        Parameter(name: "host", kind: .text),
      ], isPlural: false),
    "sources.label": Entry(parameters: [], isPlural: false),
    "sources.lanePlan": Entry(parameters: [], isPlural: false),
    "sources.official": Entry(parameters: [], isPlural: false),
    "sources.pdf": Entry(parameters: [], isPlural: false),
    "sources.pdfLabel": Entry(
      parameters: [
        Parameter(name: "label", kind: .text)
      ], isPlural: false),
    "sources.prices": Entry(parameters: [], isPlural: false),
    "state.beyondHorizon": Entry(parameters: [], isPlural: false),
    "state.beyondHorizon.body": Entry(
      parameters: [
        Parameter(name: "date", kind: .text)
      ], isPlural: false),
    "state.closed.body": Entry(
      parameters: [
        Parameter(name: "detail", kind: .text)
      ], isPlural: false),
    "state.closed.bodyNoReason": Entry(parameters: [], isPlural: false),
    "state.closed.noSessions": Entry(parameters: [], isPlural: false),
    "state.closed.other": Entry(
      parameters: [
        Parameter(name: "code", kind: .text)
      ], isPlural: false),
    "state.closed.outOfSeason": Entry(parameters: [], isPlural: false),
    "state.closed.title": Entry(parameters: [], isPlural: false),
    "state.closed.unclassified": Entry(parameters: [], isPlural: false),
    "state.closed.unmapped": Entry(
      parameters: [
        Parameter(name: "text", kind: .text)
      ], isPlural: false),
    "state.closed.unstated": Entry(parameters: [], isPlural: false),
    "state.none.body": Entry(parameters: [], isPlural: false),
    "state.none.body.phone": Entry(parameters: [], isPlural: false),
    "state.none.title": Entry(parameters: [], isPlural: false),
    "state.notStated": Entry(parameters: [], isPlural: false),
    "state.openUnscheduled": Entry(parameters: [], isPlural: false),
    "state.unlisted.body": Entry(parameters: [], isPlural: false),
    "state.unlisted.summary": Entry(
      parameters: [
        Parameter(name: "count", kind: .integer)
      ], isPlural: true),
    "state.unlisted.title": Entry(parameters: [], isPlural: false),
    "state.unrecognised": Entry(
      parameters: [
        Parameter(name: "status", kind: .text)
      ], isPlural: false),
    "status.awaiting_scrape": Entry(parameters: [], isPlural: false),
    "status.closed": Entry(parameters: [], isPlural: false),
    "status.closed_reason": Entry(
      parameters: [
        Parameter(name: "reason", kind: .text)
      ], isPlural: false),
    "status.no_source": Entry(parameters: [], isPlural: false),
    "status.uncurated": Entry(parameters: [], isPlural: false),
    "theme.auto": Entry(parameters: [], isPlural: false),
    "theme.dark": Entry(parameters: [], isPlural: false),
    "theme.light": Entry(parameters: [], isPlural: false),
    "tier.scheduled": Entry(parameters: [], isPlural: false),
    "toolbar.age": Entry(parameters: [], isPlural: false),
    "toolbar.age.adult": Entry(parameters: [], isPlural: false),
    "toolbar.age.any": Entry(parameters: [], isPlural: false),
    "toolbar.age.child": Entry(parameters: [], isPlural: false),
    "toolbar.age.senior": Entry(parameters: [], isPlural: false),
    "toolbar.age.teen": Entry(parameters: [], isPlural: false),
    "toolbar.busyness": Entry(parameters: [], isPlural: false),
    "toolbar.busynessReason": Entry(parameters: [], isPlural: false),
    "toolbar.gender": Entry(parameters: [], isPlural: false),
    "toolbar.gender.any": Entry(parameters: [], isPlural: false),
    "toolbar.gender.diverse": Entry(parameters: [], isPlural: false),
    "toolbar.gender.female": Entry(parameters: [], isPlural: false),
    "toolbar.gender.male": Entry(parameters: [], isPlural: false),
    "toolbar.label": Entry(parameters: [], isPlural: false),
    "toolbar.lapOnly": Entry(parameters: [], isPlural: false),
    "toolbar.mode.day": Entry(parameters: [], isPlural: false),
    "toolbar.mode.pool": Entry(parameters: [], isPlural: false),
    "toolbar.near": Entry(parameters: [], isPlural: false),
    "toolbar.pool": Entry(parameters: [], isPlural: false),
    "toolbar.searchPool": Entry(parameters: [], isPlural: false),
    "toolbar.view": Entry(parameters: [], isPlural: false),
    "toolbar.viewMode": Entry(parameters: [], isPlural: false),
    "toolbar.wherefrom": Entry(parameters: [], isPlural: false),
    "verdict.hasSessions": Entry(parameters: [], isPlural: false),
    "verdict.notOpenToYou": Entry(parameters: [], isPlural: false),
    "warning.calendar_coverage": Entry(
      parameters: [
        Parameter(name: "year", kind: .text)
      ], isPlural: false),
    "warning.holiday_hours_unverified": Entry(
      parameters: [
        Parameter(name: "date", kind: .text),
        Parameter(name: "pools", kind: .text),
      ], isPlural: false),
    "warning.unknown": Entry(
      parameters: [
        Parameter(name: "code", kind: .text)
      ], isPlural: false),
  ]
}
