"""Closure reasons as CODES rather than curated German prose.

`ClosureRange.reason` / `ScheduleException.reason` are hand-authored German strings
("Sommerpause", "Betriebsferien"). They reach the UI verbatim, which is why
`StatusOut.detail` is English in one branch and German in another — the mixed-language
seam the i18n plan exists to close.

The mapping runs at BUILD time (`boundary/mapping.py`, on the way from the curated DTO
into the domain), not at read time: the ETL owns the shape of curated data, and the query
layer should never have to parse prose. Once classified, the gold store carries the code
and the query layer just forwards it.

**Unmapped text fails safe, loudly.** A phrase we have not seen becomes `UNMAPPED`
carrying the original German through as a parameter, so the UI still says something true
("Closed · <the German>") rather than going blank — and `swimzh build` reports it on
stderr so a new upstream phrase surfaces as an audit line instead of silently degrading.
This is the same idiom as `LanePlanUnavailable`: persist the failure as typed state.
"""

from __future__ import annotations

from enum import StrEnum


class ClosureCode(StrEnum):
    """Why a facility or basin is shut. A closed set — extend it deliberately."""

    #: Seasonal shutdown ("Sommerpause").
    SEASONAL_BREAK = "seasonal_break"
    #: Seasonal shutdown combined with annual maintenance ("Sommerpause / Revision").
    SEASONAL_BREAK_MAINTENANCE = "seasonal_break_maintenance"
    #: Annual maintenance / overhaul ("Revision").
    MAINTENANCE = "maintenance"
    #: Company holidays ("Betriebsferien").
    OPERATIONAL_BREAK = "operational_break"
    #: Christmas Eve ("Heiligabend") — a dated exception, not a range.
    CHRISTMAS_EVE = "christmas_eve"

    # --- generated by the resolver, never by curated text ---------------------------
    #: Shut because the facility's public-holiday policy says so. Carries `holiday`.
    PUBLIC_HOLIDAY = "public_holiday"
    #: Open in principle, but nothing is scheduled for this weekday.
    NO_SESSIONS = "no_sessions"
    #: A dated exception marked closed with no stated reason.
    SPECIAL = "special"

    #: Fail-safe: curated text we could not classify. Carries `text` — the original
    #: German — so the UI stays truthful and the builder can report it.
    UNMAPPED = "unmapped"


#: Exact curated phrases → code. Matching is exact (after trimming) and
#: case-insensitive: these are authored by hand in `data/pools/*.yaml`, so fuzzy
#: matching would buy nothing and could silently mis-classify a new phrase that merely
#: resembles a known one. A miss is not a failure — it is an audit line.
_PHRASES: dict[str, ClosureCode] = {
    "sommerpause": ClosureCode.SEASONAL_BREAK,
    "sommerpause / revision": ClosureCode.SEASONAL_BREAK_MAINTENANCE,
    "revision": ClosureCode.MAINTENANCE,
    "betriebsferien": ClosureCode.OPERATIONAL_BREAK,
    "heiligabend": ClosureCode.CHRISTMAS_EVE,
}


def classify_closure(text: str | None) -> tuple[ClosureCode, dict[str, str]]:
    """Classify curated closure prose into a code + its interpolation params.

    Returns `(SPECIAL, {})` for empty text — a closure with no stated reason is a real,
    nameable state, not a failure. Anything else unrecognised is `UNMAPPED` carrying the
    original text, so nothing is ever silently dropped.
    """
    stripped = (text or "").strip()
    if not stripped:
        return ClosureCode.SPECIAL, {}
    code = _PHRASES.get(stripped.casefold())
    if code is not None:
        return code, {}
    return ClosureCode.UNMAPPED, {"text": stripped}


def is_unmapped(code: ClosureCode) -> bool:
    """Whether this code means "we could not classify it" — the audit predicate."""
    return code is ClosureCode.UNMAPPED
