// The lane derivations, replayed against the domain (S3b acceptance 3).
//
// `Fixtures/lane_plans.json` is generated by `scripts/ios_fixtures.py` from
// `swimzh.domain.lane_plan`, over the SAME offline gold build the bundled store comes from. Its
// two halves come from different code on purpose: the input `strips` are written by the
// export's own `_strip_doc`, the expected values by the domain functions applied to the
// original `LanePlan`. So this is not a mirror of the port — it is the domain, reached through
// the export's serialisation, which is the only path the phone will ever have to the data.
//
// The fixture covers all six basins that carry a parsed Belegungsplan on the committed store,
// across all seven weekdays, at four times of day — plus ONE synthetic basin, and that one is
// not decoration. `partial` is a rendered field derived from `unresolved_lanes`, and every real
// basin resolved completely, so a fixture drawn from gold alone would assert `partial == false`
// everywhere and prove nothing. The synthetic plan has an unreadable lane 4 and one block that
// covers it, so the flag is true at three probes and false at the fourth.

import Foundation
import Testing

@testable import SwimZHKit

// Since S4 the two SENTENCES this file pins — the row's lane line and the incomplete-plan
// caveat — are `Message`s rather than English strings, so the assertions render them through a
// real compiled catalog (`CatalogFixture.english`) and keep asserting the same English. The
// `partial` variants are SEPARATE keys rather than a suffix appended to a finished sentence,
// which is why nothing here builds an expected string by concatenation any more.

@Suite("Lane derivations vs the Python domain")
struct LanePlanTests {
  /// The English renderer, and the `Format` the lane counts are formatted with. One reader for
  /// both halves: a count formatted in one locale inside a sentence written in another is the
  /// mismatch `Localized` carries a `Format` to prevent.
  static let en = CatalogFixture.english
  static var format: Format { en.format }

  static let fixture: LaneFixture = {
    let url = RepoFixtures.root.appending(
      path: "apps/ios/Tests/SwimZHKitTests/Fixtures/lane_plans.json")
    // A force-try in a test fixture loader: an unreadable fixture is not a failing case, it is
    // the whole suite being unable to run, and every test below would otherwise report its own
    // confusing failure for one missing file.
    // swift-format-ignore
    let data = try! Data(contentsOf: url)
    // swift-format-ignore
    return try! JSONDecoder().decode(LaneFixture.self, from: data)
  }()

  @Test("the fixture is big enough, and varied enough, to be evidence")
  func fixtureIsNotVacuous() throws {
    let cases = Self.fixture.cases
    // The committed store carries SIX lane-plan basins, plus the synthetic one. The count is
    // asserted as a floor, never as an equality: the plan's own ledger records that an earlier
    // hard-coded "7 basins" was wrong about this very store, and a data refresh may add more.
    #expect(Set(cases.map(\.basinID)).count >= 7)
    #expect(cases.count >= 49)
    #expect(cases.contains { $0.basinID == Self.fixture.syntheticBasinID })
    // Both values of every flag that decides what a swimmer is told.
    let availabilities = cases.flatMap { $0.at.map(\.availability) }
    #expect(availabilities.contains { $0.partial })
    #expect(availabilities.contains { !$0.partial })
    #expect(availabilities.contains { $0.publicLanes > 0 })
    #expect(availabilities.contains { $0.reservedLanes > 0 })
    #expect(availabilities.contains { $0.publicUntil == nil })
    #expect(cases.contains { !$0.roster.isEmpty })
    #expect(cases.contains { $0.bestPublicDay != nil })
  }

  @Test("every stored row decodes — a malformed one would silently become an empty plan")
  func everyRowDecodes() throws {
    for row in Self.fixture.cases {
      let day = try #require(row.laneDay(), "\(row.basinID) weekday \(row.weekday)")
      #expect(day.laneCount == row.laneCount)
      #expect(day.strips.count == row.strips.count)
      #expect(day.unresolvedLanes == Set(row.unresolvedLanes))
      #expect(day.confidence == row.confidence)
    }
  }

  @Test("lane_availability_at, at four times of day on every basin and weekday")
  func availabilityMatchesTheDomain() throws {
    for row in Self.fixture.cases {
      let day = try #require(row.laneDay())
      for probe in row.at {
        let time = try #require(TimeOfDay(hhmm: probe.time))
        let context = "\(row.basinID) weekday \(row.weekday) at \(probe.time)"
        expectEqual(day.availability(at: time), probe.availability, "\(context)")
      }
    }
  }

  @Test("lane_availability_timeline cuts the session at exactly the domain's boundaries")
  func timelineMatchesTheDomain() throws {
    for row in Self.fixture.cases {
      let day = try #require(row.laneDay())
      let within = try #require(row.timeline.window())
      let segments = day.availabilityTimeline(within: within).segments
      let context = "\(row.basinID) weekday \(row.weekday)"
      #expect(segments.count == row.timeline.segments.count, "segment count: \(context)")
      for (mine, theirs) in zip(segments, row.timeline.segments) {
        #expect(mine.window.start.hhmm == theirs.start, "start: \(context)")
        #expect(mine.window.end.hhmm == theirs.end, "end: \(context)")
        expectEqual(mine.availability, theirs.availability, "\(context) \(theirs.start)")
      }
      #expect(day.availabilityTimeline(within: within).weekday == row.weekday)
    }
  }

  @Test("best_public_time, both bounded by a session and unbounded over the day")
  func bestPublicMatchesTheDomain() throws {
    for row in Self.fixture.cases {
      let day = try #require(row.laneDay())
      let within = try #require(row.timeline.window())
      let context = "\(row.basinID) weekday \(row.weekday)"
      expectEqual(day.bestPublicTime(), row.bestPublicDay, "whole day: \(context)")
      expectEqual(day.bestPublicTime(within: within), row.bestPublicWithin, "within: \(context)")
    }
  }

  @Test("club_roster, restricted to the weekday the row is keyed by")
  func rosterMatchesTheDomain() throws {
    for row in Self.fixture.cases {
      let day = try #require(row.laneDay())
      let roster = day.clubRoster()
      let context = "\(row.basinID) weekday \(row.weekday)"
      #expect(roster.count == row.roster.count, "roster size: \(context)")
      for (mine, theirs) in zip(roster, row.roster) {
        #expect(mine.club == theirs.club, "\(context)")
        #expect(mine.weekday == theirs.weekday, "\(context)")
        #expect(mine.window.start.hhmm == theirs.start, "\(context)")
        #expect(mine.window.end.hhmm == theirs.end, "\(context)")
        #expect(mine.lanes == theirs.lanes, "\(context) \(theirs.club)")
      }
    }
  }

  /// The `strips` document IS the lane day view — `lane_day_view` ran in Python before the
  /// export wrote it — so the client's view is a decode, not a second derivation. This pins
  /// that: every lane `1...lane_count` has a strip, including the empty ones, because dropping
  /// an empty lane would silently renumber the lanes below it.
  @Test("lane_day_view: one strip per lane, empty lanes kept")
  func dayViewCoversEveryLane() throws {
    for row in Self.fixture.cases {
      let day = try #require(row.laneDay())
      #expect(day.strips.map(\.lane) == Array(1...day.laneCount), "\(row.basinID)")
    }
    let synthetic = try #require(
      Self.fixture.cases.first { $0.basinID == Self.fixture.syntheticBasinID }?.laneDay())
    #expect(synthetic.strips.contains { $0.holds.isEmpty }, "no empty lane to prove the point")
  }

  /// `ZurichClock.weekday(of:)` is the DATE → LANE-PLAN join — `Store.laneDays` reads
  /// `lane_day WHERE weekday = ?` through it — and nothing exercised it end to end. An
  /// off-by-one there would be silent: every real basin publishes a plan for all seven
  /// weekdays, so the wrong day still returns a full, plausible plan (a club's Sunday
  /// reservations drawn on a Wednesday) with every gate green.
  ///
  /// The weekday is derived here from `DateFormatter`, NOT from the function under test, so
  /// this is an oracle rather than a restatement. It has teeth because the six real basins
  /// carry genuinely different strips on different weekdays (they are identical to each
  /// other, but not across the week), so reading the wrong row changes the answer.
  @Test("the store joins a DATE to that weekday's own lane plan, not to a neighbouring one")
  func storeJoinsTheRightWeekdaysPlan() async throws {
    let names = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    let formatter = DateFormatter()
    formatter.locale = Locale(identifier: "en_US_POSIX")
    formatter.timeZone = ZurichClock.timeZone
    formatter.dateFormat = "EEEE"
    let noon = TimeOfDay(hour: 12, minute: 0)
    let store = try Store.bundled()
    let metadata = try await store.metadata()
    var checked = 0
    var weekdaysSeen: Set<Int> = []
    for offset in 0..<7 {
      guard let day = ZurichClock.day(metadata.horizonStart, plus: offset) else { continue }
      let instant = try #require(ZurichClock.instant(day: day, at: noon))
      let weekday = try #require(names.firstIndex(of: formatter.string(from: instant)))
      weekdaysSeen.insert(weekday)
      let answer = try await store.answer(onDay: day, at: noon, for: Person())
      for option in answer.options {
        guard let served = option.laneDayView else { continue }
        let row = try #require(
          Self.fixture.cases.first { $0.basinID == option.basinID && $0.weekday == weekday },
          "no fixture case for \(option.basinID) weekday \(weekday)")
        let expected = try #require(row.laneDay())
        #expect(served.strips == expected.strips, "\(option.basinID) on \(day)")
        checked += 1
      }
    }
    #expect(weekdaysSeen.count == 7, "seven consecutive days must cover the whole week")
    #expect(checked > 5, "only \(checked) options carried a lane plan — this proved little")
  }

  /// A four-lane basin: lanes 1-2 public all morning, lane 3 held by a club until 09:00 and
  /// public after, lane 4 unreadable. The lane-3 handover is what makes the summary's two
  /// answers distinguishable — without it every probe would read "2 of 4" and the test would
  /// pass whichever moment it used.
  static func fixtureDay() throws -> LaneDay {
    try #require(
      LaneDay.decode(
        basinID: "b", weekday: 1, laneCount: 4,
        strips: #"""
          [{"lane":1,"segments":[{"start":"06:00","end":"12:00","access":"PublicSwim","owner":null}]},
           {"lane":2,"segments":[{"start":"06:00","end":"12:00","access":"PublicSwim","owner":null}]},
           {"lane":3,"segments":[{"start":"06:00","end":"09:00","access":"ClubReserved","owner":"ASVZ"},
                                 {"start":"09:00","end":"12:00","access":"PublicSwim","owner":null}]},
           {"lane":4,"segments":[]}]
          """#,
        unresolvedLanes: "[4]", confidence: "partial"))
  }

  static let fixtureWindow = TimeWindow(
    start: TimeOfDay(hour: 6, minute: 0), end: TimeOfDay(hour: 12, minute: 0))

  /// The option `Store.options` would build for `fixtureDay()` at `time`.
  ///
  /// `openAtQueryTime` is DERIVED from the same `time` the availability is read at, exactly as
  /// the store derives it (`Store.swift`: `openAtQueryTime(window, at: time)`). The earlier
  /// version took it as a free parameter, which decoupled the flag from the instant and meant
  /// the coupling the summary rule depends on was never exercised at all.
  static func option(day: LaneDay, at time: TimeOfDay) -> SwimOption {
    let window = fixtureWindow
    return SwimOption(
      poolID: "p", poolName: "Pool", poolKind: "indoor", basinID: "b", basinName: "25m",
      lengthM: 25, lanes: 4, window: window, access: .publicSwim, weather: "any",
      eligibility: eligibility(Person(), .publicSwim),
      openAtQueryTime: openAtQueryTime(window, at: time), price: nil,
      distanceKm: nil,
      laneAvailability: day.availability(at: time),
      laneTimeline: day.availabilityTimeline(within: window),
      laneDayView: day,
      laneBestPublic: day.bestPublicTime(within: window))
  }

  @Test("the row's lane line describes the SESSION, not the wall clock")
  func laneSummaryIsNotAWallClockClaim() throws {
    // Found on a real screen at 04:00: `lane_availability` is the split AT THE QUERIED INSTANT,
    // so a session opening at 06:00 reported "no lanes open to the public" beside the words
    // "Opens 06:00". The instant is a fact about the clock; the line is a fact about the
    // session — and the two are only the same thing while the session is running.
    let day = try Self.fixtureDay()
    let before = Self.option(day: day, at: TimeOfDay(hour: 4, minute: 0))
    #expect(before.openAtQueryTime == false, "derived from 04:00, not asserted by hand")
    #expect(before.laneAvailability?.publicLanes == 0, "the field itself stays at query time")
    // The SENTENCE, rendered — a key would be a weaker claim, and the number in it is the whole
    // point of the test.
    let beforeLine = try #require(before.laneSummary(isToday: true, format: Self.format))
    #expect(Self.en(beforeLine) == "2 of 4 lanes open — some lanes unreadable")
    // While it IS running, the live split is exactly what a swimmer wants.
    let during = Self.option(day: day, at: TimeOfDay(hour: 10, minute: 0))
    #expect(during.openAtQueryTime, "derived from 10:00, inside 06:00-12:00")
    let duringLine = try #require(during.laneSummary(isToday: true, format: Self.format))
    #expect(Self.en(duringLine) == "3 of 4 lanes open — some lanes unreadable")
  }

  @Test("off today the live split is never spoken, however open the session looks")
  func laneSummaryMakesNoWallClockClaimOffToday() throws {
    // The half-fix. `openAtQueryTime` is pure time-of-day containment, and off today the app
    // asks the store at the fixed `DAY_MOMENT` of 12:00 — so the flag says "covers midday",
    // which is true of essentially every long session, and the row would print a midday split
    // as if it were happening. Off today only the OPENING split is a claim the row can make.
    let day = try Self.fixtureDay()
    // 11:00 is inside the session, so `openAtQueryTime` is true and the live split differs from
    // the opening one — which is precisely the discrimination the old test could not make.
    let midday = Self.option(day: day, at: TimeOfDay(hour: 11, minute: 0))
    #expect(midday.openAtQueryTime, "the flag is true — and off today that means nothing")
    #expect(midday.laneAvailability?.publicLanes == 3)
    let live = try #require(midday.laneSummary(isToday: true, format: Self.format))
    #expect(Self.en(live) == "3 of 4 lanes open — some lanes unreadable")
    let offToday = try #require(midday.laneSummary(isToday: false, format: Self.format))
    #expect(Self.en(offToday) == "2 of 4 lanes open — some lanes unreadable")
    // And the off-today answer is the session's OPENING split, not some third number. Asserted
    // on the MESSAGE — same key, same params, same count — so it holds in every language and
    // not merely in the one whose sentences happen to coincide.
    let opening = try #require(midday.laneTimeline?.segments.first?.availability)
    #expect(midday.laneSummary(isToday: false, format: Self.format) == opening.summary(Self.format))
  }

  @Test("the printed line and the spoken fact agree on the same off-today row")
  func spokenAndPrintedLaneFactsAgree() throws {
    // They disagreed: `a11yFacts` has always read the OPENING split (`segments.first`) while
    // the line read the live one, so VoiceOver and the pixels said different numbers about one
    // row. Both are session-level claims now, and this pins them together.
    let day = try Self.fixtureDay()
    let option = Self.option(day: day, at: TimeOfDay(hour: 11, minute: 0))
    // The fact lives on the `lanes` variant, which needs a timeline and NO day view — so the
    // input is built without one rather than relying on a store row that never produces it.
    let input = RibbonOptionInput(
      access: option.access.kind, start: option.window.start.hhmm, end: option.window.end.hhmm,
      facility: option.poolName, basin: option.basinName,
      laneTimeline: option.laneTimeline.map(RibbonTimelineInput.init(timeline:)),
      laneDayView: nil,
      laneBestPublic: option.laneBestPublic.map(RibbonPublicWindow.init(window:)))
    let ribbon = optionRibbon(input)
    #expect(ribbon.variant == "lanes", "the fact under test only exists on this variant")
    let spoken = try #require(
      a11yFacts(for: ribbon, in: Self.en).first { $0.label == Message("a11y.fact.publicLanes") })
    // "2 of 4" — the OPENING split, which is what the printed line says off today too.
    #expect(Self.en(spoken.value) == "2 of 4")
    let printed = Self.en(try #require(option.laneSummary(isToday: false, format: Self.format)))
    #expect(printed.hasPrefix(Self.en(spoken.value)))
    // The agreement is about the NUMBERS, not about English word order: the spoken fact and the
    // printed line are two sentences and no language has to open one with the other. So in all
    // five, both must name the same public count and the same total — checked by rendering the
    // pair of counts through each language's own `Format` and requiring both to appear.
    for (language, localized) in CatalogFixture.all {
      let counts = Format(AppLocale(language))
      let message = try #require(option.laneSummary(isToday: false, format: counts))
      let line = localized(message)
      let heard = try #require(
        a11yFacts(for: ribbon, in: localized)
          .first { $0.label == Message("a11y.fact.publicLanes") })
      let fact = localized(heard.value)
      for number in [counts.integer(2), counts.integer(4)] {
        #expect(line.contains(number), "\(language): the line dropped \(number)")
        #expect(fact.contains(number), "\(language): the spoken fact dropped \(number)")
      }
    }
  }

  @Test("the incomplete-plan caveat is one sentence with one polarity")
  func incompleteCaveatHasOnePolarity() throws {
    // It was written twice, in two wordings, with OPPOSITE polarities: the Gantt tested
    // `confidence != "complete"`, the detail sheet `confidence == "partial"`. Any token that is
    // neither made one surface shout and the other stay silent about the same basin.
    let partial = try Self.fixtureDay()
    #expect(!partial.isComplete)
    let caveat = try #require(partial.incompleteLanesCaveat)
    #expect(Self.en(caveat).contains("could not be read"))
    // One sentence in EVERY language, and a real one: a key that never reached the catalog
    // would render as itself and read as a design choice rather than as a hole.
    for (language, localized) in CatalogFixture.all {
      let said = localized(caveat)
      #expect(said != caveat.key, "\(language) has no translation for \(caveat.key)")
      #expect(!said.isEmpty)
    }
    // Only a KNOWN-complete plan is presented as complete. An unknown token is caveated, which
    // is the safe direction: a caveat on a full plan is noise, its absence on a broken one is
    // a lie.
    for token in ["partial", "", "unknown", "COMPLETE", "complete "] {
      let day = LaneDay(
        basinID: "b", weekday: 1, laneCount: 4, strips: partial.strips,
        unresolvedLanes: partial.unresolvedLanes, confidence: token)
      #expect(day.incompleteLanesCaveat == caveat, "token \(token) must be caveated")
    }
    let complete = LaneDay(
      basinID: "b", weekday: 1, laneCount: 4, strips: partial.strips,
      unresolvedLanes: [], confidence: LaneDay.completeConfidence)
    #expect(complete.isComplete)
    #expect(complete.incompleteLanesCaveat == nil)
    // And the token really is the one the export writes: every committed row is one of the two.
    let tokens = Set(Self.fixture.cases.map(\.confidence))
    #expect(tokens.contains(LaneDay.completeConfidence))
    #expect(tokens.isSubset(of: [LaneDay.completeConfidence, "partial"]))
  }

  @Test("zero public lanes is worded as a state, never as a measurement")
  func zeroPublicLanesIsAState() throws {
    let day = try Self.fixtureDay()
    // "0 of 4 lanes open" reads as a count somebody measured; "no lanes open to the public" is
    // what the plan actually says.
    let empty = day.availability(at: TimeOfDay(hour: 20, minute: 0))
    #expect(empty.publicLanes == 0)
    #expect(Self.en(empty.summary(Self.format)).hasPrefix("no lanes open to the public"))
    #expect(!Self.en(empty.summary(Self.format)).contains("0 of"))
    // An incomplete plan says so, because the count is a floor rather than a number. It is its
    // OWN key now, not the base sentence with a clause appended: the clause lands elsewhere in
    // German and cannot be appended at all in Polish without re-inflecting what precedes it.
    let sevenAM = day.availability(at: TimeOfDay(hour: 7, minute: 0))
    #expect(Self.en(sevenAM.summary(Self.format)).contains("unreadable"))
    #expect(sevenAM.summary(Self.format).key.hasSuffix(".partial"))
    // The zero rule in EVERY language, because "0 of 4" is a shape a translator can reintroduce
    // for free — the base and the partial keys both have to stay out of the counting entry.
    for (language, localized) in CatalogFixture.all {
      let counts = Format(AppLocale(language))
      let zero = localized(empty.summary(counts))
      #expect(!zero.contains(counts.integer(0)), "\(language): \"\(zero)\" counts zero lanes")
      #expect(zero != empty.summary(counts).key, "\(language) has no translation")
      // ...and it is NOT the counting sentence: the two keys stay distinct whatever the words.
      let counted = day.availability(at: TimeOfDay(hour: 10, minute: 0))
      #expect(counted.publicLanes > 0)
      #expect(localized(counted.summary(counts)) != zero, "\(language): both split states agree")
    }
  }

  @Test("a basin with no published plan has NO lane line at all")
  func noPlanMeansNoLine() {
    // Not an empty string, and not "0 lanes": a pool with no Belegungsplan must never render
    // as a pool with no free lanes.
    let window = TimeWindow(
      start: TimeOfDay(hour: 9, minute: 0), end: TimeOfDay(hour: 17, minute: 0))
    let option = SwimOption(
      poolID: "p", poolName: "Pool", poolKind: "indoor", basinID: "b", basinName: "Hauptbecken",
      lengthM: 25, lanes: nil, window: window, access: .publicSwim, weather: "any",
      eligibility: eligibility(Person(), .publicSwim), openAtQueryTime: true, price: nil,
      distanceKm: nil)
    #expect(option.laneSummary(isToday: true, format: Self.format) == nil)
    #expect(option.laneSummary(isToday: false, format: Self.format) == nil)
  }

  @Test("a malformed row decodes to nil, never to a plan with no reservations")
  func malformedRowsAreNotEmptyPlans() {
    // An empty plan reads as "no lane is reserved" — a claim. Absence is not a claim, and the
    // caller degrades to the ribbon that says the split is not published.
    #expect(
      LaneDay.decode(
        basinID: "x", weekday: 1, laneCount: 4, strips: "not json",
        unresolvedLanes: "[]", confidence: "complete") == nil)
    #expect(
      LaneDay.decode(
        basinID: "x", weekday: 1, laneCount: 4,
        strips:
          #"[{"lane":1,"segments":[{"start":"25:99","end":"09:00","access":"PublicSwim","owner":null}]}]"#,
        unresolvedLanes: "[]", confidence: "complete") == nil)
  }
}

/// One availability, compared field by field so a failure names WHICH fact drifted rather than
/// dumping two structs.
private func expectEqual(
  _ mine: LaneAvailability,
  _ theirs: LaneFixture.Availability,
  _ context: String
) {
  #expect(mine.laneCount == theirs.laneCount, "lane_count: \(context)")
  #expect(mine.publicLanes == theirs.publicLanes, "public_lanes: \(context)")
  #expect(mine.reservedLanes == theirs.reservedLanes, "reserved_lanes: \(context)")
  #expect(mine.owners == theirs.owners, "owners: \(context)")
  #expect(mine.publicUntil?.hhmm == theirs.publicUntil, "public_until: \(context)")
  #expect(mine.partial == theirs.partial, "partial: \(context)")
}

private func expectEqual(
  _ mine: PublicWindow?,
  _ theirs: LaneFixture.Window?,
  _ context: String
) {
  #expect((mine == nil) == (theirs == nil), "presence: \(context)")
  guard let mine, let theirs else { return }
  #expect(mine.window.start.hhmm == theirs.start, "start: \(context)")
  #expect(mine.window.end.hhmm == theirs.end, "end: \(context)")
  #expect(mine.publicLanes == theirs.publicLanes, "public_lanes: \(context)")
}

/// The generated file, as the test reads it.
struct LaneFixture: Decodable {
  struct Availability: Decodable {
    let laneCount: Int
    let publicLanes: Int
    let reservedLanes: Int
    let owners: [String]
    let publicUntil: String?
    let partial: Bool

    private enum CodingKeys: String, CodingKey {
      case laneCount = "lane_count"
      case publicLanes = "public_lanes"
      case reservedLanes = "reserved_lanes"
      case owners
      case publicUntil = "public_until"
      case partial
    }
  }

  struct Window: Decodable {
    let start: String
    let end: String
    let publicLanes: Int

    private enum CodingKeys: String, CodingKey {
      case start
      case end
      case publicLanes = "public_lanes"
    }
  }

  struct Probe: Decodable {
    let time: String
    let availability: Availability
  }

  struct Segment: Decodable {
    let start: String
    let end: String
    let availability: Availability
  }

  struct Timeline: Decodable {
    let within: [String]
    let segments: [Segment]

    func window() -> TimeWindow? {
      guard within.count == 2, let start = TimeOfDay(hhmm: within[0]),
        let end = TimeOfDay(hhmm: within[1])
      else { return nil }
      return TimeWindow(start: start, end: end)
    }
  }

  struct Slot: Decodable {
    let club: String
    let weekday: Int
    let start: String
    let end: String
    let lanes: [Int]
  }

  /// The stored `strips` document. `Codable` in BOTH directions on purpose: the test re-encodes
  /// it and feeds the string to `LaneDay.decode`, so the production decoder is what runs rather
  /// than a test-only shortcut around it.
  struct StripDoc: Codable {
    struct Segment: Codable {
      let start: String
      let end: String
      let access: String
      let owner: String?
    }

    let lane: Int
    let segments: [Segment]
  }

  struct Case: Decodable {
    let basinID: String
    let weekday: Int
    let laneCount: Int
    let strips: [StripDoc]
    let unresolvedLanes: [Int]
    let confidence: String
    let at: [Probe]
    let timeline: Timeline
    let bestPublicDay: Window?
    let bestPublicWithin: Window?
    let roster: [Slot]

    private enum CodingKeys: String, CodingKey {
      case basinID = "basin_id"
      case weekday
      case laneCount = "lane_count"
      case strips
      case unresolvedLanes = "unresolved_lanes"
      case confidence
      case at
      case timeline
      case bestPublicDay = "best_public_day"
      case bestPublicWithin = "best_public_within"
      case roster
    }

    /// The row as the STORE would hand it over: the strips re-encoded to the JSON text the
    /// `lane_day` column holds, then decoded by the production decoder.
    func laneDay() -> LaneDay? {
      guard let data = try? JSONEncoder().encode(strips),
        let json = String(data: data, encoding: .utf8),
        let lanes = try? JSONEncoder().encode(unresolvedLanes),
        let laneJSON = String(data: lanes, encoding: .utf8)
      else { return nil }
      return LaneDay.decode(
        basinID: basinID,
        weekday: weekday,
        laneCount: laneCount,
        strips: json,
        unresolvedLanes: laneJSON,
        confidence: confidence
      )
    }
  }

  let syntheticBasinID: String
  let cases: [Case]

  private enum CodingKeys: String, CodingKey {
    case syntheticBasinID = "synthetic_basin_id"
    case cases
  }
}
